stage: dev
nextcloud_image_tag: latest
nextcloud:
  nbc:
    urls:
      hydraUrl: oauth-nbc-main.cd.dbildungscloud.dev
      nextcloud_hostname: "{%if namespace == 'nbc-main'%}nextcloud-nbc.dbildungscloud.dev{%else%}{{ namespace + '.sc-dev-nextcloud.dbildungscloud.dev'}}{%endif%}"
      collabora: collabora.niedersachsen.dbildungscloud.dev
    plugins:
      install: "{{ nextcloud_install_plugins_default }}"
      enabled: "{{ nextcloud_enable_plugins_default }}"
      disabled: "{{ nextcloud_disable_plugins_default }}"
    theming:
      slogan: Niedersächsische Bildungscloud
      theming_color: '#5083C7'
      logo_url: https://niedersachsen.cloud/images/logo/logo-wt.png
  brb:
    urls:
      hydraUrl: oauth-brb-main.cd.dbildungscloud.dev
      nextcloud_hostname: "{%if namespace == 'brb-main'%}nextcloud-brb.dbildungscloud.dev{%else%}{{ namespace + '.sc-dev-nextcloud.dbildungscloud.dev'}}{%endif%}"
      collabora: collabora.brandenburg.dbildungscloud.dev
    plugins:
      install: "{{ nextcloud_install_plugins_default }}"
      enabled: "{{ nextcloud_enable_plugins_default }}"
      disabled: "{{ nextcloud_disable_plugins_default }}"
    theming:
      slogan: Schul-Cloud Brandenburg
      theming_color: '#EE2B45'
      logo_url: https://brandenburg.cloud/images/logo/logo-only.png
  thr:
    urls:
      hydraUrl: oauth-default-main.cd.dbildungscloud.dev
      nextcloud_hostname: "{%if namespace == 'thr-main'%}nextcloud-thr.dbildungscloud.dev{%else%}{{ namespace + '.sc-dev-nextcloud.dbildungscloud.dev'}}{%endif%}"
      collabora: collabora.thueringen.dbildungscloud.dev
    plugins:
      install: "{{ nextcloud_install_plugins_default }}"
      enabled: "{{ nextcloud_enable_plugins_default }}"
      disabled: "{{ nextcloud_disable_plugins_default }}"
    theming:
      name: Thüringer Schulcloud Nextcloud
      slogan: Thüringer Schulcloud
      theming_color: '#185888'
      logo_url: https://schulcloud-thueringen.de/images/logo/logo-bild-mono.svg

nextcloud_instances:
- name: nbc
  namespace: nbc-main
  vault: "{{project}}-{{stage}}-cd"
  nextcloud_enabled: true
  # set this var to true in order for the configure.sh script to be run
  # run_nextcloud_configuration: false
- name: brb
  namespace: brb-main
  vault: "{{project}}-{{stage}}-cd"
  nextcloud_enabled: true
- name: thr
  namespace: thr-main
  vault: "{{project}}-{{stage}}-cd"
  nextcloud_enabled: true

nextcloud_resources:
  limits:
    cpu: 1000m
    memory: 4G
  requests:
    cpu: 500m
    memory: 2G
