stage: dev
nextcloud_image_tag: latest
nextcloud:
  nbc:
    urls:
      authorizeUrl: oauth-nbc-main.cd.dbildungscloud.dev
      hydraUrl: oauth-nbc-main.cd.dbildungscloud.dev
      logoutUrl: nbc-main.cd.dbildungscloud.dev
      nextcloud_hostname: nextcloud-nbc.dbildungscloud.dev
      collabora: collabora.niedersachsen.dbildungscloud.dev
    plugins:
      install: "{{ nextcloud_install_plugins_default }}"
      enabled: "{{ nextcloud_enable_plugins_default }}"
      disabled: "{{ nextcloud_disable_plugins_default }}"
    theming:
      "{{ nbc_nextcloud_theming }}"
  brb:
    urls:
      authorizeUrl: oauth-brb-main.cd.dbildungscloud.dev
      hydraUrl: oauth-brb-main.cd.dbildungscloud.dev
      logoutUrl: brb-main.cd.dbildungscloud.dev
      nextcloud_hostname: nextcloud-brb.dbildungscloud.dev
      collabora: collabora.brandenburg.dbildungscloud.dev
    plugins:
      install: "{{ nextcloud_install_plugins_default }}"
      enabled: "{{ nextcloud_enable_plugins_default }}"
      disabled: "{{ nextcloud_disable_plugins_default }}"
  thr:
    urls:
      authorizeUrl: oauth-default-main.cd.dbildungscloud.dev
      hydraUrl: oauth-default-main.cd.dbildungscloud.dev
      logoutUrl: default-main.cd.dbildungscloud.dev
      nextcloud_hostname: nextcloud-thr.dbildungscloud.dev
      collabora: collabora.thueringen.dbildungscloud.dev
    plugins:
      install: "{{ nextcloud_install_plugins_default }}"
      enabled: "{{ nextcloud_enable_plugins_default }}"
      disabled: "{{ nextcloud_disable_plugins_default }}"

nextcloud_instances:
- name: nbc
  namespace: nbc-main
  vault: "{{project}}-{{stage}}-cd"
  nextcloud_enabled: true
  # set this var to true in order for the configure.sh script to be run
  # run_nextcloud_configuration: false
  authorizeUrl: "{{ nextcloud.nbc.urls.authorizeUrl }}"
  hydraUrl: "{{ nextcloud.nbc.urls.hydraUrl }}"
  logoutUrl: "{{ nextcloud.nbc.urls.logoutUrl }}"
  nextcloud_hostname: "{{ nextcloud.nbc.urls.nextcloud_hostname }}"
- name: brb
  namespace: brb-main
  vault: "{{project}}-{{stage}}-cd"
  nextcloud_enabled: true
  authorizeUrl: "{{ nextcloud.brb.urls.authorizeUrl }}"
  hydraUrl: "{{ nextcloud.brb.urls.hydraUrl }}"
  logoutUrl: "{{ nextcloud.brb.urls.logoutUrl }}"
  nextcloud_hostname: "{{ nextcloud.brb.urls.nextcloud_hostname }}"
- name: thr
  namespace: thr-main
  vault: "{{project}}-{{stage}}-cd"
  nextcloud_enabled: true
  authorizeUrl: "{{ nextcloud.thr.urls.authorizeUrl }}"
  hydraUrl: "{{ nextcloud.thr.urls.hydraUrl }}"
  logoutUrl: "{{ nextcloud.thr.urls.logoutUrl }}"
  nextcloud_hostname: "{{ nextcloud.thr.urls.nextcloud_hostname }}"

nextcloud_resources:
  limits:
    cpu: 1000m
    memory: 4G
  requests:
    cpu: 500m
    memory: 2G