# values set via Github Action
# edusharing_crawler_helm_chart_version:
# edusharing_crawler_image_tag:

edusharing_instance_secret_name: edusharing-instance
edusharing_kubernetes_service_name: http://edusharing-repository-service.{{ namespace }}.svc.cluster.local:8081/edu-sharing/
sodix_secret_name: sodix-secret
# alter this
h5p_s3_bucket: s3-web-bucket
# fwu_s3_bucket: s3-web-bucket

edusharing_secrets:
- name: "{{ edusharing_instance_secret_name }}"
- name: "{{ sodix_secret_name }}"
- name: "{{ h5p_s3_bucket }}"

splash_url: http://splash.edusharing.svc.cluster.local:8050
splash_helm_chart_version: "1.0.2"
splash_helm_chart_values:
  service:
    port: 8050
  resources:
    limits:
      cpu: 1750m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  serviceAccount:
    create: false

edusharing_crawler_list:
- name: hello-world
  enabled: false
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: hello_world
  - name: SCHEDULE
    value: "*-*-2:00"
- name: oeh-spider
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
  - name: CRAWLER
    value: oeh_spider
  - name: SCHEDULE
    value: "*-*-20:00"
  - name: LOG_LEVEL
    value: "INFO"
  - name: SPLASH_URL
    value: "{{ splash_url }}"
  - name: DRY_RUN
    value: "False"
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: SODIX_USER
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: username
  - name: SODIX_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: password
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: mediothek-pixiothek-spider
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 750m
      memory: 2Gi
  env:
  - name: CRAWLER
    value: mediothek_pixiothek_spider
  - name: SCHEDULE
    value: "*-*-21:00"
  - name: SPLASH_URL
    value: "{{ splash_url }}"
  - name: LOG_LEVEL
    value: "INFO"
  - name: DRY_RUN
    value: "False"
  - name: SODIX_USER
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: username
  - name: SODIX_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: password
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: merlin-spider
  enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: merlin_spider
  - name: SCHEDULE
    value: "*-*-22:00"
  - name: SPLASH_URL
    value: "{{ splash_url }}"
  - name: LOG_LEVEL
    value: "INFO"
  - name: DRY_RUN
    value: "False"
  - name: SODIX_USER
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: username
  - name: SODIX_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: password
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: sodix-spider
  enabled: true
  resources:
    limits:
      cpu: 1200m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 1Gi
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: sodix_spider
  - name: SCHEDULE
    value: "*-*-3:00"
  - name: SPLASH_URL
    value: "{{ splash_url }}"
  - name: LOG_LEVEL
    value: "INFO"
  - name: DRY_RUN
    value: "False"
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
  - name: SODIX_USER
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: username
  - name: SODIX_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: password
- name: sodix-permissions
  enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: sodix_permissions
  - name: SCHEDULE
    value: "*-*-22:40"
  - name: LOG_LEVEL
    value: "INFO"
  - name: SODIX_BLACKLIST_PATH
    value: "/oeh-search-etl/schulcloud/sodix/blacklist.json"
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: h5p-upload
  enabled: false
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: h5p_upload
  - name: SCHEDULE
    value: "*-*-00:00"
  - name: LOG_LEVEL
    value: "INFO"
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
  - name: S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: "{{ h5p_s3_bucket }}"
        key: s3_access_key
  - name: S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: "{{ h5p_s3_bucket }}"
        key: s3_access_secret
  - name: S3_ENDPOINT_URL
    value: "{{ s3_url_frankfurt }}"
  - name: S3_BUCKET_NAME
    value: "lernstore-content"
  - name: S3_DOWNLOAD_DIRECTORY
    value: "s3_download"
- name: fwu-upload
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: fwu_upload
  - name: SCHEDULE
    value: "*-*-01:00"
  - name: LOG_LEVEL
    value: "INFO"
  - name: EDU_SHARING_BASE_URL
    value: "{{ edusharing_kubernetes_service_name }}"
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
  - name: S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: "{{ h5p_s3_bucket }}"
        key: s3_access_key
  - name: S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: "{{ h5p_s3_bucket }}"
        key: s3_access_secret
  - name: S3_ENDPOINT_URL
    value: "{{ s3_url_frankfurt }}"
  - name: S3_BUCKET_NAME
    value: "fwu-content"

edusharing_2_crawler_list: ['fwu-upload']