# values set via Github Action
# edusharing_crawler_helm_chart_version:
#edusharing_crawler_image_tag:

# not used - defaults
edusharing_crawler_repository: ghcr.io/hpi-schul-cloud/oeh-search-etl
edusharing_crawler_image_name: "edusharing-crawler"

# sgrink down without values
edusharing_crawler_list:
hello_world_values:
  crawler:
    name: hello-world
    enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: hello_world
  - name: SCHEDULE
    value:  '*-*-10:48'
  service:
    internalPort: 8080
# - values:
#     crawler:
#       name: hello-world2
#       enabled: true
#       schedule: '*-*-10:50'
#     image:
#       tag: "{{ edusharing_crawler_image_tag }}"
#     env:
#     - name: test-env
#       value: "my test env"
# - values:
#     crawler:
#       name: hello_world2
#       enabled: true
#     schedule: '*-*-14:30'
#     image:
#       tag: "{{ edusharing_crawler_image_tag }}"