# values set via Github Action
# edusharing_crawler_helm_chart_version:
# edusharing_crawler_image_tag:

# secrets are currently only in infra-dev available (same on every stage?)
edusharing_instance_secret_name: edusharing-instance
sodix_secret_name: sodix-secret
h5p_s3_bucket: s3-web-bucket

# does this change or should be dynamic?
pyppeter_ws_endpoint: "ws://localhost:3000"

edusharing_crawler_list:
- name: hello-world
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: hello_world
  - name: SCHEDULE
    value: "*-*-13:19"
- name: mediothek-pixiothek-spider
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
  - name: CRAWLER
    value: mediothek_pixiothek_spider
  - name: SCHEDULE
    value: "*-*-13:20"
  - name: LOG_LEVEL
    value: "INFO"
  - name: PYPPETEER_WS_ENDPOINT
    value: "{{ pyppeter_ws_endpoint }}"
  - name: DRY_RUN
    value: "False"
  - name: EDU_SHARING_BASE_URL
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: url
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: merlin-spider
  enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: merlin_spider
  - name: SCHEDULE
    value: "*-*-13:20"
  - name: LOG_LEVEL
    value: "INFO"
  - name: MODE
    value: "edu-sharing"
  - name: PYPPETEER_WS_ENDPOINT
    value: "{{ pyppeter_ws_endpoint }}"
  - name: DRY_RUN
    value: "False"
  - name: EDU_SHARING_BASE_URL
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: url
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: sodix-spider
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: sodix_spider
  - name: SCHEDULE
    value: "*-*-13:20"
  - name: LOG_LEVEL
    value: "INFO"
  - name: MODE
    value: "edu-sharing"
  - name: PYPPETEER_WS_ENDPOINT
    value: "{{ pyppeter_ws_endpoint }}"
  - name: DRY_RUN
    value: "False"
  - name: EDU_SHARING_BASE_URL
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: url
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
  - name: SODIX_USER
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: password
  - name: SODIX_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ sodix_secret_name }}"
        key: password
- name: sodix-permissions
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: sodix_permissions
  - name: SCHEDULE
    value: "*-*-13:20"
  - name: LOG_LEVEL
    value: "INFO"
  - name: PYPPETEER_WS_ENDPOINT
    value: "{{ pyppeter_ws_endpoint }}"
  - name: SODIX_BLACKLIST_PATH
    value: "/oeh-search-etl/schulcloud/sodix/blacklist.json"
  - name: EDU_SHARING_BASE_URL
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: url
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
- name: h5p-upload
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  enabled: true
  image:
    tag: "{{ edusharing_crawler_image_tag }}"
  env:
  - name: CRAWLER
    value: h5p_upload
  - name: SCHEDULE
    value: "*-*-13:20"
  - name: LOG_LEVEL
    value: "INFO"
  - name: EDU_SHARING_BASE_URL
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: url
  - name: EDU_SHARING_USERNAME
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: username
  - name: EDU_SHARING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ edusharing_instance_secret_name }}"
        key: password
  - name: S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: "{{ h5p_s3_bucket }}"
        key: s3_access_key
  - name: S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: "{{ h5p_s3_bucket }}"
        key: s3_access_secret
  - name: S3_ENDPOINT_URL
    value: "http://s3-eu-central-1.ionoscloud.com/"
  - name: "S3_BUCKET_NAME"
    value: "lernstore-content"
  - name: S3_DOWNLOAD_DIRECTORY
    value: "s3_download"
