---
- name: Delete Namespace
  hosts:
    - nextcloud
  connection: local
  roles:
  - kubeconfig
  tasks:
  - name: Delete Namespace
    kubernetes.core.k8s:
      name: "{{ namespace }}"
      kind: Namespace
      state: absent
      kubeconfig: "{{ kubeconfig }}"
      api_version: v1
    when:  namespace !=  "nbc-main"
