---
- name: Delete Bucket
  hosts:
    - nextcloud
  connection: local
  # change s3 access key and secret from nextloud ionos user to normal ionos user
  tasks:
  - name: Delete s3 bucket
    amazon.aws.s3_bucket:
      access_key: "{{ s3_access_key }}"
      secret_key: "{{ s3_access_secret }}"
      name: "{{ s3_bucket_name }}"
      state: absent
      endpoint_url: "{{ s3_url_berlin }}"
      region: "{{ s3_region_berlin }}"
      force: true