---
- name: Deploy to Edusharing Clusters
  hosts:
    - edusharing
  connection: local
  tasks:
  - name: Add Helm Chart Repo dbildungscloud
    kubernetes.core.helm_repository:
      name: dbildungscloud
      repo_url: "https://hpi-schul-cloud.github.io/helm-charts-registry"
    # run also in check mode since later task depends on this step 
    check_mode: false

  - name: Add Helm Chart Repo ntppool
    kubernetes.core.helm_repository:
      name: ntppool
      repo_url: "https://charts.ntppool.org/"
    # run also in check mode since later task depends on this step 
    check_mode: false

  - name: Create secrets for edusharing
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      definition:
        apiVersion: onepassword.com/v1
        kind: OnePasswordItem
        metadata:
          name: "{{ item.name }}"
          namespace: "{{ namespace }}"
        spec:
          itemPath: "vaults/{{ vault }}/items/{{ item.name }}"
    loop: "{{ edusharing_secrets }}"

  - name: Install Splash - Javascript rendering engine
    kubernetes.core.helm:
      name: "splash"
      chart_ref: "ntppool/splash"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ splash_helm_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ namespace }}"
      values:
        "{{ splash_helm_chart_values }}"
        
  - name: Install browserless chromium
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: "browserless-chromium"
          namespace: "{{ namespace }}"
          labels:
            app: browserless-chromium
            app.kubernetes.io/part-of: schulcloud-verbund
            app.kubernetes.io/version: v2.24.2
            app.kubernetes.io/name: chromium
            app.kubernetes.io/component: browserless
            app.kubernetes.io/managed-by: ansible
        spec:
          replicas: 1
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1
          revisionHistoryLimit: 4
          paused: false
          selector:
            matchLabels:
              app: browserless-chromium
          template:
            metadata:
              labels:
                app: browserless-chromium
                app.kubernetes.io/part-of: schulcloud-verbund
                app.kubernetes.io/version: v2.24.2
                app.kubernetes.io/name: chromium
                app.kubernetes.io/component: browserless
                app.kubernetes.io/managed-by: ansible
            spec:
              securityContext:
                runAsUser: 999
                runAsGroup: 999
                fsGroup: 999
                runAsNonRoot: true
              containers:
              - name: chromium
                image: ghcr.io/browserless/chromium:v2.24.2
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: 3000
                  name: chromium
                  protocol: TCP
                resources:
                  limits:
                    cpu: "4000m"
                    memory: "4Gi"
                  requests:
                    cpu: "100m"
                    memory: "256Mi"
                env:
                - name: TIMEOUT
                  value: "120000"

  - name: Install browserless chromium Service
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "browserless-chromium"
          namespace: "{{ namespace }}"
          labels:
            app: browserless-chromium
            app.kubernetes.io/part-of: schulcloud-verbund
            app.kubernetes.io/name: chromium
            app.kubernetes.io/component: browserless
            app.kubernetes.io/managed-by: ansible
        spec:
          type: ClusterIP
          clusterIP: None
          ports:
            - port: 3000
              targetPort: 3000
              protocol: TCP
              name: chromium
          selector:
            app: browserless-chromium

  - name: Install Crawler for Edusharing
    kubernetes.core.helm:
      name: "crawler-{{item.name}}"
      chart_ref: "dbildungscloud/edusharing-crawler"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ edusharing_crawler_helm_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ namespace }}"
      values:
        "{{ item }}"
    when: item.enabled and namespace == "edusharing"
    loop: "{{ edusharing_crawler_list }}"

  - name: Install Crawler for edu-2 dev instance
    kubernetes.core.helm:
      name: "crawler-{{item.name}}"
      chart_ref: "dbildungscloud/edusharing-crawler"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ edusharing_crawler_helm_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ namespace }}"
      values:
        "{{ item }}"
    when: item.enabled and namespace == "edu-2"
    loop: "{{ edusharing_2_crawler_list }}"
