---
- name: Deploy to Edusharing Clusters
  hosts:
    - edusharing
  connection: local
  roles:
    - kubeconfig
  tasks:
  - name: Add Helm Chart Repo
    kubernetes.core.helm_repository:
      name: dbildungscloud
      repo_url: "https://hpi-schul-cloud.github.io/helm-charts/"

  - name: Install Helm Chart
    kubernetes.core.helm:
      name: "edusharing-crawler"
      chart_ref: "dbildungscloud/edusharing-crawler"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ edusharing_crawler_helm_chart_version }}"
      kubeconfig: ~/.kube/config
      release_namespace: "{{ namespace }}"
      # values:
      #   "{{ edusharing_crawler_values }}"
