---
- name: Deploy to Edusharing Clusters
  hosts:
    - edusharing
  connection: local
  tasks:
  - name: Add Helm Chart Repo dbildungscloud
    kubernetes.core.helm_repository:
      name: dbildungscloud
      repo_url: "https://hpi-schul-cloud.github.io/helm-charts-registry"

  - name: Add Helm Chart Repo ntppool
    kubernetes.core.helm_repository:
      name: ntppool
      repo_url: "https://charts.ntppool.org/"

  - name: Create secrets for edusharing
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      definition:
        apiVersion: onepassword.com/v1
        kind: OnePasswordItem
        metadata:
          name: "{{ item.name }}"
          namespace: "{{ namespace }}"
        spec:
          itemPath: "vaults/{{ vault }}/items/{{ item.name }}"
    loop: "{{ edusharing_secrets }}"

  - name: Install Splash - Javascript rendering engine
    kubernetes.core.helm:
      name: "splash"
      chart_ref: "ntppool/splash"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ splash_helm_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ namespace }}"
      values:
        "{{ splash_helm_chart_values }}"

  - name: Install Crawler for Edusharing
    kubernetes.core.helm:
      name: "crawler-{{item.name}}"
      chart_ref: "dbildungscloud/edusharing-crawler"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ edusharing_crawler_helm_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ namespace }}"
      values:
        "{{ item }}"
    when: item.enabled and namespace == "edusharing"
    loop: "{{ edusharing_crawler_list }}"

  - name: Install Crawler for edusharing-2 dev instance
    kubernetes.core.helm:
      name: "crawler-{{item.name}}"
      chart_ref: "dbildungscloud/edusharing-crawler"
      update_repo_cache: yes
      wait: yes
      chart_version: "{{ edusharing_crawler_helm_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ namespace }}"
      values:
        "{{ item }}"
    when: item.enabled and namespace == "edusharing-2"
    loop: "{{ edusharing_2_crawler_list }}"