---
- name: Nextcloud Deployment
  hosts:
    - sc-dev-nextcloud
  connection: local
  tasks:
  - name: Add nextcloud chart repo
    kubernetes.core.helm_repository:
      name: nextcloud
      repo_url: "https://nextcloud.github.io/helm/"

  - name: Create a namespace based on branch
    kubernetes.core.k8s:
      name: "{{ namespace }}"
      kind: Namespace
      state: present
      kubeconfig: "{{ kubeconfig }}"
      api_version: v1
    when:  namespace not in  ["nbc-main", "brb-main", "thr-main"]

  - name: Create s3 bucket
    amazon.aws.aws_s3:
      access_key: "{{ s3_access_key }}"
      secret_key: "{{ s3_access_secret }}"
      name: "{{ namespace }}"
      state: create
      s3_url: "{{ s3_url_berlin }}"
      region: "{{ s3_region_berlin }}"
    when: namespace not in  ["nbc-main", "brb-main", "thr-main"]

  - name: Create Nextcloud instances (one instance)
    include_tasks: multi-instance-nextcloud.yml
    vars:
      instance_vault: "{{ item.vault | default( project + '-' + stage + '-' + item.name) }}"
    loop: "{{ nextcloud_instances | selectattr('nextcloud_enabled', 'defined' ) | selectattr('nextcloud_enabled', 'equalto', true) | selectattr('name', 'equalto', instance_name)}}"
    when:  instance_name != 'all'
    tags:
      - nextcloud
      - nextcloud-cron

  - name: Create Nextcloud instances (all)
    include_tasks: multi-instance-nextcloud.yml
    vars:
      instance_vault: "{{ item.vault | default( project + '-' + stage + '-' + item.name) }}"
    loop: "{{ nextcloud_instances | selectattr('nextcloud_enabled', 'defined' ) | selectattr('nextcloud_enabled', 'equalto', true) }}"
    when: instance_name == 'all'
    tags:
      - nextcloud
      - nextcloud-cron