---
name: EDU rerun setup

on:
  workflow_call:
    inputs:
      CLUSTER:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
      PROXY_URL:
        required: false
        type: string
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true
      PROXY_CREDENTIALS:
        required: false

jobs:
  run_ansible_playbook_edusharing:
    environment: ${{ inputs.CLUSTER }}
    runs-on: ubuntu-latest
    env:
      K8S_AUTH_PROXY: ${{ inputs.PROXY_URL }}
      K8S_AUTH_PROXY_HEADERS_PROXY_BASIC_AUTH: ${{ secrets.PROXY_CREDENTIALS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "repo/infra-deploy"
          repository: hpi-schul-cloud/infra-deploy

      - name: Install requirements python3
        shell: bash
        run: |
          python3 -m pip install kubernetes

      - name: Install requirements ansible-galaxy
        working-directory: ${{ github.workspace }}/repo/infra-deploy/
        run: ansible-galaxy install -r ansible/collections/requirements.yml

      - name: Create Kubeconfig file
        working-directory: ${{ github.workspace }}/
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Set ENVs in config.yml file
        working-directory: ${{ github.workspace }}/repo/infra-deploy/ansible/group_vars
        run: |
          echo -e "\nnamespace: ${{ inputs.NAMESPACE }}" >> config.yml
          cat config.yml

      - name: Execute Ansible Edusharing Setup Playbook
        working-directory: ${{ github.workspace }}/repo/infra-deploy/
        run: ansible-playbook ansible/edusharing-setup-playbook.yml --inventory-file hosts -e 'ansible_python_interpreter=/usr/bin/python3' -l ${{ inputs.CLUSTER }}

      - name: Delete kubeconfig files
        if: always()
        working-directory: ${{ github.workspace }}
        run: |
          rm -f kubeconfig
