---
name: EDU Update Crawler

on:
  workflow_call:
    inputs:
      CLUSTER:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        required: true
        type: string
      EDUSHARING_CRAWLER_IMAGE_TAG:
        required: true
        type: string
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true

jobs:
  run_ansible_playbook_edusharing:
    environment: ${{ inputs.CLUSTER }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "repo/infra-deploy"
          repository: hpi-schul-cloud/infra-deploy

      - name: Install requirements python3
        shell: bash
        run: |
          tree
          python3 -m pip install kubernetes

      - name: Install requirements ansible-galaxy
        run: ansible-galaxy install -r repo/infra-deploy/ansible/collections/requirements.yml

      - name: Create Kubeconfig file in config folder
      # here
        working-directory: ${{ github.workspace }}/
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          ls -la

      - name: Set ENVs in config.yml file
        working-directory: ${{ github.workspace }}/repo/infra-deploy/ansible/group_vars
        run: |
          echo -e "\nnamespace: ${{ inputs.NAMESPACE }}" >> config.yml
          echo "edusharing_crawler_helm_chart_version: ${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}" >> config.yml
          echo "edusharing_crawler_image_tag: ${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}" >> config.yml
          cat config.yml

      - name: Execute Ansible Edusharing Crawler Playbook
        working-directory: ${{ github.workspace }}/
        run: ansible-playbook repo/infra-deploy/ansible/edusharing-crawler-playbook.yml --inventory-file hosts -e 'ansible_python_interpreter=/usr/bin/python3' -l ${{ inputs.CLUSTER }}

      - name: Delete config files
        if: always()
      # here
        working-directory: ${{ github.workspace }}/kubeconfig
        run: |
          rm -rf /config
          ls -la





