name: EDU Deploy Crawler
on:
  # cd schulcloud-nextcloud
  # gh workflow run edu-dev-crawler.yml --ref <branch-name> (-f EDUSHARING_CRAWLER_HELM_CHART_VERSION=<version> -f EDUSHARING_CRAWLER_IMAGE_TAG=<version>)
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: "Select Edusharing cluster"
        required: true
        # change default back to infra-dev-edusharing or delete defaults
        default: sc-staging-edusharing
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.0.02"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "0.0.15"

jobs:
  # approve_edusharing:
  #   environment: approve_edusharing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized approve_edusharing Group has been given!"


# not working yet
  set_namespace:
      # needs:
      # - approve_edusharing
    runs-on: ubuntu-latest
    env:
      CLUSTER: ${{ inputs.CLUSTER }}
    outputs:
      branch: ${{ steps.set_namespace.outputs.namespace }}
    steps:
      - name: Set namespace
        shell: bash
        run: |
          # on sc-staging-edusharing cluster we have to use the dev-edusharing-namespace
          echo "Set namespace..."
          if [ ${{ env.CLUSTER }} == sc-staging-edusharing ]
          then
            namespace_name=$(echo "namespace=dev-edusharing")
            echo "namespace_name=dev-edusharing" >> $GITHUB_ENV
            echo "$namespace_name" >> $GITHUB_OUTPUT
            echo "namespace is set to $namespace_name"
          else
            echo "edusharing" >> $GITHUB_OUTPUT
            echo "edusharing"
          fi
        id: set_namespace

  deploy_edusharing_crawlers:
    uses: ./.github/workflows/edu-deploy-crawler.yml
    needs:
      - set_namespace
    with:
      CLUSTER: "${{ inputs.CLUSTER }}"
      NAMESPACE: ${{ needs.set_namespace.outputs.namespace }}
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}