name: EDU Rerun Setup for Dev
on:
  workflow_dispatch:
    inputs:
      EDUSHARING_NAMESPACE:
        description: "Select valid namespace: 'edusharing', 'edu-2'"
        required: true
        type: choice
        options:
        - "edusharing"
        - "edu-2"

jobs:
  dev_deploy_edusharing_setup:
    uses: ./.github/workflows/edu-deploy-setup.yml
    with:
      CLUSTER: sc-dev-edusharing
      NAMESPACE: "${{ inputs.EDUSHARING_NAMESPACE }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      PROXY_CREDENTIALS: ${{ secrets.PROXY_CREDENTIALS }}


