name: Deploy Edusharing Crawler on Dev
on:
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: "Select sc-dev-edusharing cluster"
        required: true
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true

jobs:
# ask if wanted
  # dev_edusharing_approval:
  #   environment: dev_edusharing_crawler_approve
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized dev_edusharing_crawler_approve Group has been given!"

  # deployment to sc-dev-edusharing cluster
  dev_deploy_edusharing_crawlers:
    # if: "{{ inputs.CLUSTER }}" == "sc-dev-edusharing"
    uses: ./.github/workflows/deploy-crawler.yml
    needs:
      - dev_deploy_edusharing_crawlers
    with:
      CLUSTER: "{{ inputs.CLUSTER }}"
      NAMESPACE: "github-actions-test" # dev-edusharing
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "0.1.0" # "{{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      # not used yet - set in Ansible vars
      EDUSHARING_CRAWLER_IMAGE_TAG: "0.1.0"  # "{{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}


