name: EDU Deploy Crawler
on:
  # cd schulcloud-nextcloud
  # gh workflow run edu-crawler.yml --ref <branch-name> (-f CLUSTER=<cluster-name>  -f EDUSHARING_CRAWLER_HELM_CHART_VERSION=<version> -f EDUSHARING_CRAWLER_IMAGE_TAG=<version>)
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: "Select Edusharing cluster"
        required: true
        default: sc-dev-edusharing
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.1.0"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "edusharing-crawler-0.4.20"

jobs:
  approve_edusharing:
    environment: approve_edusharing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval from authorized approve_edusharing Group has been given!"

  deploy_edusharing_crawlers:
    uses: ./.github/workflows/edu-deploy-crawler.yml
    needs:
      - approve_edusharing
    with:
      CLUSTER: "${{ inputs.CLUSTER }}"
      NAMESPACE: edusharing
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}