name: Deploy Edusharing Crawler
on:
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: "Select Edusharing cluster"
        required: true
        default: infra-dev-edusharing-1
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.1.3"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "0.0.5"

jobs:
  # edusharing_approval:
  #   environment: edusharing_crawler_approve
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized edusharing_crawler_approve Group has been given!"

  set_namespace:
      # needs:
      # - edusharing_approval
    runs-on: ubuntu-latest
    steps:
      - name: Set namespace
        shell: bash
        run: |
          # on sc-staging-edusharing cluster we have to use the dev-edusharing-namespace
          echo "Set namespace!"
          if ${{ inputs.CLUSTER }} == "sc-staging-edusharing"
          then
            echo "namespace=dev-edusharing" >> $GITHUB_OUTPUT
            echo "namespace set to dev-edusahring"
          else
            echo "namespace=edusharing" >> $GITHUB_OUTPUT
          fi
        id: set_namespace

  deploy_edusharing_crawlers:
    uses: ./.github/workflows/edu-deploy-crawler.yml
    # needs:
    #   - edusharing_approval
    with:
      CLUSTER: "${{ inputs.CLUSTER }}"
      NAMESPACE: "github-actions-test" # ${{ needs.set_namespace.outputs.namespace }}
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}