name: EDU Deploy Crawler to Dev
on:
  # cd schulcloud-nextcloud
  # gh workflow run edu-dev-crawler.yml --ref <branch-name> (-f EDUSHARING_CRAWLER_HELM_CHART_VERSION=<version> -f EDUSHARING_CRAWLER_IMAGE_TAG=<version>)
  workflow_dispatch:
    inputs:
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.1.0"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "0.1.10"
      EDUSHARING_NAMESPACE:
        description: "Select valid namespace: 'edusharing', 'edu-2'"
        required: true

jobs:
  dev_deploy_edusharing_crawlers:
    if: ${{ inputs.CLUSTER }} == "sc-dev-edusharing"
    uses: ./.github/workflows/edu-deploy-crawler.yml
    with:
      CLUSTER: sc-dev-edusharing
      NAMESPACE: "${{ inputs.EDUSHARING_NAMESPACE }}"
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}


