name: Deploy Edusharing Crawler on Dev
on:
  #gh workflow run edu-dev-crawler.yml --ref <branch-name>
  workflow_dispatch:
    inputs:
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.1.4"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "latest"
jobs:
  dev_deploy_edusharing_crawlers:
    if: "{{ inputs.CLUSTER }}" == "sc-dev-edusharing"
    uses: ./.github/workflows/edu-deploy-crawler.yml
    with:
      CLUSTER: sc-dev-edusharing
      NAMESPACE: "edusharing"
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}


