name: EDU Deploy Crawler
on:
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: "Select Edusharing cluster"
        required: true
        # change default back to infra-dev-edusharing or delete defaults
        default: sc-staging-edusharing
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.1.5"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "0.0.10"

jobs:
  # approve_edusharing:
  #   environment: approve_edusharing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized approve_edusharing Group has been given!"

  set_namespace:
      # needs:
      # - approve_edusharing
    runs-on: ubuntu-latest
    steps:
      - name: Set namespace
        shell: bash
        run: |
          # on sc-staging-edusharing cluster we have to use the dev-edusharing-namespace
          echo "Set namespace!"
          if ${{ inputs.CLUSTER }} == "sc-staging-edusharing"
          then
            echo "namespace=dev-edusharing" >> $GITHUB_OUTPUT
            echo "namespace set to dev-edusahring"
          else
            echo "namespace=edusharing" >> $GITHUB_OUTPUT
          fi
        id: set_namespace

  deploy_edusharing_crawlers:
    uses: ./.github/workflows/edu-deploy-crawler.yml
    needs:
      - set_namespace
    with:
      CLUSTER: "${{ inputs.CLUSTER }}"
      NAMESPACE:  dev-edusharing # ${{ needs.set_namespace.outputs.namespace }} #github-actions-test
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}