name: Deploy Edusharing Crawler
# decide if default valuee should be set or not
on:
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: "Select Edusharing cluster"
        required: true
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Select Edusharing crawler Helm Chart version"
        required: true
        default: "0.1.0"
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Select Edusharing crawler Image Tag"
        required: true
        default: "0.1.0"
  # paths:
  #   - 'edusharing/**'

jobs:
  # edusharing_approval:
  #   environment: edusharing_crawler_approve
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized edusharing_crawler_approve Group has been given!"

  set_namespace:
      # needs:
      # - edusharing_approval
    runs-on: ubuntu-latest
    steps:
      - name: Set namespace
        shell: bash
        run: |
          echo "Set namespace!"
          if ${{ inputs.CLUSTER }} == "sc-staging-edusharing"
          then
            echo "namespace=dev-edusharing" >> $GITHUB_OUTPUT
            echo "namespace set to dev-edusahring"
          else
            echo "namespace=edusharing" >> $GITHUB_OUTPUT
          fi
        id: set_namespace

  # should we limit this to clusters, or should it also be able to rollot to sc-dev?
  # deployment to all cluster possible except sc-dev-edusharing
  deploy_edusharing_crawlers:
    # if: "{{ inputs.CLUSTER }}" != "sc-dev-edusharing"
    uses: ./.github/workflows/deploy-crawler.yml
    # needs:
    #   - edusharing_approval
    with:
      CLUSTER: "${{ inputs.CLUSTER }}"
      NAMESPACE: "github-actions-test" # ${{ needs.set_namespace.outputs.branch }}
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "${{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      # not used yet - set in Ansible vars
      EDUSHARING_CRAWLER_IMAGE_TAG: "${{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}