name: Deploy Edusharing Crawler
on: push
  # paths:
  #   - 'edusharing/**'


  # workflow_dispatch:
  #   inputs:
  #     EDUSHARING_CRAWLER_HELM_CHART_VERSION:
  #       description: 'Edusharing crawler Helm Chart version'
  #       required: true
  #     EDUSHARING_CRAWLER_IMAGE_VERSION:
  #       description: "Edusharing crawler image version"
  #       required: false
  #       default: all
  #     STAGE:
  #       description: "Select Edusharing cluster"
  #       required: false
  #       default: all

jobs:
  # edusharing_approval:
  #   # stages have to be adjusted
  #   environment: dev_edusharing_crawler_approve
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized dev_edusharing_crawler_approve Group has been given!"

  get_branch_name:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        # this is outdated may want to upgrade
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  deploy_edusharing_crawlers:
    #if: inputs.execute_group == inputs.host_name || inputs.execute_group == inputs.host_group || inputs.execute_group == inputs.host_stage || inputs.execute_group == 'all'
    needs:
      - get_branch_name
    uses: ./.github/workflows/deploy.yml
    with:
      HOST: "infra-dev-edusharing-1"
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "0.1.0"
      EDUSHARING_CRAWLER_IMAGE_NAME: "ghademo-0.1.0"
      EDUSHARING_CRAWLER_IMAGE_TAG: ""
      BRANCH: ${{ needs.branch_name.outputs.branch }}
      # for development process use this branch name, since name of branch is too long, after that use branch name trimmed?
      # https://github.com/marketplace/actions/truncate-string
      # for edusharing crawler namespace should be "edusharing"?
      NAMESPACE: "github-actions-test"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

  deployment_successful:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment was successful"