name: Deploy Edusharing Crawler
on: push
  # paths:
  #   - 'edusharing/**'

  workflow_dispatch:
    inputs:
      EDUSHARING_CRAWLER_HELM_CHART_VERSION:
        description: "Edusharing crawler Helm Chart version"
        required: true
      EDUSHARING_CRAWLER_IMAGE_TAG:
        description: "Edusharing crawler Image Tag"
        required: true
      HOST:
        description: "Select Edusharing cluster"
        required: true

jobs:
  edusharing_approval:
    environment: edusharing_crawler_approve
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval from authorized edusharing_crawler_approve Group has been given!"

  # deployment to all cluster except sc-dev-edusharing
  deploy_edusharing_crawlers:
    if: "{{ inputs.HOST }}" != "sc-dev-edusharing"
    uses: ./.github/workflows/deploy-crawler.yml
    needs:
      - deploy_edusharing_crawlers
    with:
      HOST: "{{ inputs.HOST }}"
      NAMESPACE: "github-actions-test" # edusharing
      EDUSHARING_CRAWLER_HELM_CHART_VERSION: "0.1.0" # "{{ inputs.EDUSHARING_CRAWLER_HELM_CHART_VERSION }}"
      # not used yet - set in Ansible vars
      EDUSHARING_CRAWLER_IMAGE_TAG: "0.1.0"  # "{{ inputs.EDUSHARING_CRAWLER_IMAGE_TAG }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}