name: NC Delete Namespace on Branch Deletion

# cd schulcloud-nextcloud
# gh workflow run nextcloud-branch-deletion.yml --ref <branch-name>
on: [delete, workflow_dispatch]

jobs:
  delete_namespace_and_buckets:
    # protect nbc-main namespace from accidental deletion
    if: ${{ needs.get_branch_name.outputs.branch }} != 'nbc-main'
    needs:
      - get_branch_name
    uses: ./.github/workflows/nextcloud-deletion.yml
    with:
      CLUSTER: sc-dev-nextcloud
      BUCKET_NAME: ${{ needs.get_branch_name.outputs.branch }}
      NAMESPACE: ${{ github.event.ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      S3ACCESSKEY: ${{ secrets.S3ACCESSKEY }}
      S3ACCESSSECRET: ${{ secrets.S3ACCESSSECRET }}