---
name: NC Delete Namespace

on:
  workflow_call:
    inputs:
      CLUSTER:
        required: true
        type: string
      BUCKET_NAME:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true
      S3ACCESSKEY:
        required: true
      S3ACCESSSECRET:
        required: true

jobs:
  run_delete_ansible_playbook:
    environment:  ${{ inputs.CLUSTER }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install requirements python3
        shell: bash
        run: |
          python3 -m pip install -r requirements.txt

      - name: Install requirements ansible-galaxy
        working-directory: ${{ github.workspace }}/ansible/repo/infra-deploy/
        run: ansible-galaxy install -r repo/infra-deploy/ansible/collections/requirements.yml

      - name: Create Kubeconfig file
        working-directory: ${{ github.workspace }}/
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Set ENVs in config.yml file
        working-directory: ${{ github.workspace }}/repo/infra-deploy/ansible/group_vars
        run: |
          echo -e "\nnamespace: ${{ inputs.NAMESPACE }}" >> config.yml
          echo "s3_access_key: ${{ secrets.S3ACCESSKEY }}" >> config.yml
          echo "s3_access_secret: ${{ secrets.S3ACCESSSECRET }}" >> config.yml
          echo "s3_bucket_name: ${{ inputs.BUCKET_NAME }}" >> config.yml
          cat config.yml

      - name: Execute Ansible Delete Bucket
        working-directory: ${{ github.workspace }}/ansible/repo/infra-deploy/
        run: ansible-playbook ansible/delete-bucket-playbook.yml --inventory-file hosts -e 'ansible_python_interpreter=/usr/bin/python3' -v -l ${{ inputs.CLUSTER }}

      - name: Execute Ansible Delete Namespace
        working-directory: ${{ github.workspace }}/ansible/repo/infra-deploy/
        run: ansible-playbook ansible/delete-namespace-playbook.yml --inventory-file hosts -e 'ansible_python_interpreter=/usr/bin/python3' -v -l ${{ inputs.CLUSTER }}

      - name: Delete kubeconfig file
        if: always()
        working-directory: ${{ github.workspace }}
        run: rm -f kubeconfig