name: NC Delete Namespace and Bucket

# cd schulcloud-nextcloud
# gh workflow run nextcloud-branch-deletion.yml -f NAMESPACE_NAME=ops-3853-ingress-test-2
on:
  workflow_dispatch:
    inputs:
      NAMESPACE_NAME:
        description: "Select namespace to delete"
        required: true

jobs:
  delete_namespace_and_buckets:
    if: ${{ inputs.NAMESPACE_NAME }} != 'nbc-main'
    uses: ./.github/workflows/nextcloud-deletion.yml
    with:
      CLUSTER: sc-dev-nextcloud
      BUCKET_NAME: ${{inputs.NAMESPACE_NAME }}
      NAMESPACE: ${{inputs.NAMESPACE_NAME }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      S3ACCESSKEY: ${{ secrets.S3ACCESSKEY }}
      S3ACCESSSECRET: ${{ secrets.S3ACCESSSECRET }}